services:
  cr3-user-api-test:
    image: cr3-user-api
    env_file:
      - .env.test
    volumes:
      - .:/usr/src/app
    # this profile prevents this service from running on typical startup
    profiles: ["test"] 
    command: pytest -x
